### ISSUE TITLE
Two directories in src/svg/patterns

### ISSUE THREAD

**Issue by chbrandt** [afrigeri/geologic-symbols-qgis#13]
The directories
* [src/svg/patterns/fgdc](https://github.com/afrigeri/geologic-symbols-qgis/tree/master/src/svg/patterns/fgdc)
* [src/svg/patterns/fgcd](https://github.com/afrigeri/geologic-symbols-qgis/tree/master/src/svg/patterns/fgcd)
seem to provide the same content. Could one of them be a typo during add/commit that persistet to the repo?

**Comment by afrigeri** [comment]
Yes it was a typo, the right directory was fgdc (for Federal Geographic Data Committee - wrong directory has been deleted,  [fixed here](https://github.com/afrigeri/geologic-symbols-qgis/commit/d45388ab38c0c845875b06fc4d74fac72570e548).

Thanks @chbrandt!

**Comment by chbrandt** [comment]
Thanks @afrigeri .
Though I think the _dist_ package (https://github.com/afrigeri/geologic-symbols-qgis/blob/master/dist/geologic_symbols_qgis.zip) still have the old/wrong directory. Could you double-check that, please?
